-- PostgreSQL Schema for mbktech.org (mbkcore ecosystem standardized)

-- Table: mbkcore_blocked_entries
CREATE TABLE IF NOT EXISTS mbkcore_blocked_entries (
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    type character varying(50) NOT NULL,
    value character varying(255) NOT NULL,
    reason text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_by character varying(255),
    is_active boolean DEFAULT true,
    CONSTRAINT mbkcore_blocked_entries_pkey PRIMARY KEY (id),
    CONSTRAINT mbkcore_blocked_entries_type_value_key UNIQUE (type, value),
    CONSTRAINT chk_mbkcore_blocked_entries_type CHECK (((type)::text = ANY ((ARRAY['email'::character varying, 'phone'::character varying, 'keyword'::character varying])::text[])))
);

CREATE INDEX IF NOT EXISTS idx_mbkcore_blocked_entries_is_active ON mbkcore_blocked_entries USING btree (is_active);
CREATE INDEX IF NOT EXISTS idx_mbkcore_blocked_entries_type_value ON mbkcore_blocked_entries USING btree (type, value);

-- Table: mbkcore_support_submissions
CREATE TABLE IF NOT EXISTS mbkcore_support_submissions (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ticket_number character varying(50),
    subject character varying(100) NOT NULL,
    support_type character varying(100),
    project_category character varying(200),
    blog_category character varying(200),
    name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    phone_number character varying(50),
    message text NOT NULL,
    rating integer,
    status character varying(50) DEFAULT 'pending'::character varying,
    priority character varying(20) DEFAULT 'normal'::character varying,
    page_url text,
    submission_timestamp timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    last_updated timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    assigned_to character varying(255),
    admin_notes text,
    resolution_notes text,
    audit_trail jsonb DEFAULT '[]'::jsonb,
    additional_fields jsonb DEFAULT '{}'::jsonb,
    CONSTRAINT mbkcore_support_submissions_pkey PRIMARY KEY (id),
    CONSTRAINT mbkcore_support_submissions_ticket_number_key UNIQUE (ticket_number),
    CONSTRAINT mbkcore_support_submissions_rating_check CHECK (((rating >= 1) AND (rating <= 5))),
    CONSTRAINT chk_mbkcore_support_submissions_priority CHECK (((priority)::text = ANY ((ARRAY['low'::character varying, 'normal'::character varying, 'high'::character varying, 'urgent'::character varying])::text[]))),
    CONSTRAINT chk_mbkcore_support_submissions_status CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'in_progress'::character varying, 'resolved'::character varying, 'closed'::character varying, 'on_hold'::character varying])::text[])))
);

CREATE INDEX IF NOT EXISTS idx_mbkcore_support_submissions_email ON mbkcore_support_submissions USING btree (email);
CREATE INDEX IF NOT EXISTS idx_mbkcore_support_submissions_status ON mbkcore_support_submissions USING btree (status);
CREATE INDEX IF NOT EXISTS idx_mbkcore_support_submissions_subject ON mbkcore_support_submissions USING btree (subject);
CREATE INDEX IF NOT EXISTS idx_mbkcore_support_submissions_timestamp ON mbkcore_support_submissions USING btree (submission_timestamp);

-- Backward-compatibility views for legacy queries
CREATE OR REPLACE VIEW support_submissions AS SELECT * FROM mbkcore_support_submissions;
CREATE OR REPLACE VIEW blocked_entries AS SELECT * FROM mbkcore_blocked_entries;
